llm_base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
llm_api_key = "sk-0237d0b3d163451586a7e01394d995e5"
llm_model = "Qwen2.5-VL-32B-Instruct"
ocr_llm_model = "Qwen2.5-VL-32B-Instruct"
ocr_llm_base_url ="http://localhost:18888/v1"
ocr_llm_api_key= "sk-1"
image_llm_model = "Qwen2.5-VL-32B-Instruct"
image_llm_base_url ="http://localhost:18888/v1"
image_llm_api_key= "sk-1"
audio_llm_model = "qwen-omni-turbo-latest"
video_llm_model = "qwen-omni-turbo-latest"